name: Release module
on:
  push:
    tag: ['*']


permissions:
  contents: read # needed for checkout
  packages: write # needed for GHCR access

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
      - name: Lint
        run: |
          timoni mod lint ./timoni
      - name: Test instance build
        run: |
          timoni build -n testing test ./timoni
      - name: Push
        run: |
          timoni mod push ./timoni \
            oci://ghcr.io/${{ github.repository_owner }}/modules/home \
            --version ${{ github.ref_name }} \
            --creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

